"""
Fetch and parse data from hero-siege-helper.vercel.app.
Supports: quests, runewords, runes, items, farm (zone drop locations).
Uses simple HTTP GET + BeautifulSoup (no headless browser needed).
Items and farm data are parsed from JS bundles (data embedded in client-side code).
"""
import re
import json
import logging

import requests
from bs4 import BeautifulSoup, Tag

from src.consts.logger import LOGGING_NAME

BASE_URL = "https://hero-siege-helper.vercel.app"
TIMEOUT = 15


def _fetch_soup(path: str) -> BeautifulSoup | None:
    logger = logging.getLogger(LOGGING_NAME)
    try:
        resp = requests.get(f"{BASE_URL}{path}", timeout=TIMEOUT)
        resp.raise_for_status()
        logger.info(f"Fetched {path} ({len(resp.text)} bytes)")
        return BeautifulSoup(resp.text, "html.parser")
    except Exception as e:
        logger.error(f"Fetch failed for {path}: {e}")
        return None


def _find_quest_container(soup: BeautifulSoup) -> Tag | None:
    """Find the Suspense boundary div that holds all quest cards."""
    marker = soup.find('h2', class_='chakra-heading',
                        string=lambda s: s and 'Questline' in str(s))
    if marker:
        card = marker.find_parent(class_='chakra-card')
        if card:
            return card.parent
    return None


def _parse_autogenerated_panel(panel: Tag) -> dict:
    """Extract quest name, description, objectives from an Autogenerated tabpanel."""
    quest = {"name": "", "description": "", "objectives": []}
    for p in panel.find_all('p'):
        text = p.get_text(strip=True)
        if text.startswith("Quest:"):
            quest["name"] = text[len("Quest:"):].strip()
        elif text.startswith("Description:"):
            quest["description"] = text[len("Description:"):].strip()
        elif "Objective:" in text:
            obj = text.split("Objective:", 1)[1].strip()
            if obj:
                quest["objectives"].append(obj)
    for li in panel.find_all('li'):
        text = li.get_text(strip=True)
        if "Objective:" in text:
            obj = text.split("Objective:", 1)[1].strip()
            if obj and obj not in quest["objectives"]:
                quest["objectives"].append(obj)
    return quest


def _parse_custom_panel(panel: Tag) -> dict:
    """Extract enriched data (locations, descriptions) from Custom Description tabpanel."""
    result = {"description": "", "locations": [], "objectives": []}
    # Description is the first <p> tag
    first_p = panel.find('p')
    if first_p:
        result["description"] = first_p.get_text(strip=True)

    seen_locations = set()
    for li in panel.find_all('li'):
        text = li.get_text(separator=' ', strip=True)
        # Location markers: 📍 followed by zone ID and name
        loc_match = re.search(r'📍\s*(\d+-\d+)\s+(.+?)(?:\s*📝|$)', text)
        if loc_match:
            zone_id = loc_match.group(1)
            zone_name = loc_match.group(2).strip()
            loc_str = f"{zone_id} {zone_name}"
            if zone_name and loc_str not in seen_locations:
                seen_locations.add(loc_str)
                result["locations"].append(loc_str)
        # Objectives
        obj_match = re.search(r'📝\s*(.+)', text)
        if obj_match:
            obj = obj_match.group(1).strip()
            if obj and obj not in result["objectives"]:
                result["objectives"].append(obj)
    return result


def _parse_quest_card(card: Tag) -> dict | None:
    """Parse a single quest card (may have tabs or just body text)."""
    panels = card.find_all(attrs={'role': 'tabpanel'})

    if len(panels) >= 2:
        # Has Custom Description + Autogenerated tabs
        custom = _parse_custom_panel(panels[0])
        auto = _parse_autogenerated_panel(panels[1])
        return {
            "name": auto["name"],
            "description": custom["description"] or auto["description"],
            "description_auto": auto["description"],
            "objectives": auto["objectives"] or custom["objectives"],
            "locations": custom["locations"],
        }
    elif len(panels) == 1:
        # Only Autogenerated tab
        auto = _parse_autogenerated_panel(panels[0])
        return {
            "name": auto["name"],
            "description": auto["description"],
            "description_auto": auto["description"],
            "objectives": auto["objectives"],
            "locations": [],
        }

    # No tabs — parse body directly
    body = card.find(class_='chakra-card__body')
    if not body:
        return None
    quest = {"name": "", "description": "", "description_auto": "", "objectives": [], "locations": []}
    for p in body.find_all('p'):
        text = p.get_text(strip=True)
        if text.startswith("Quest:"):
            quest["name"] = text[len("Quest:"):].strip()
        elif text.startswith("Description:"):
            desc = text[len("Description:"):].strip()
            quest["description"] = desc
            quest["description_auto"] = desc
        elif "Objective:" in text:
            obj = text.split("Objective:", 1)[1].strip()
            if obj:
                quest["objectives"].append(obj)
    return quest if quest["name"] else None


def fetch_quests() -> list[dict] | None:
    """
    Fetch and parse all quests from hero-siege-helper.

    Returns list of questlines:
    [
        {
            "questline": "Sarcaster Questline",
            "quests": [
                {
                    "name": "Sarcaster's Coffee beans",
                    "description": "...",
                    "description_auto": "...",
                    "objectives": ["Coffee beans collected"],
                    "locations": ["1-2 Town of Inoya"],
                },
                ...
            ]
        },
        ...
    ]
    """
    logger = logging.getLogger(LOGGING_NAME)
    soup = _fetch_soup("/quests")
    if not soup:
        return None

    container = _find_quest_container(soup)
    if not container:
        logger.error("Could not find quest container in page")
        return None

    top_cards = container.find_all(
        class_=lambda c: c and 'chakra-card' in c, recursive=False
    )
    logger.info(f"Found {len(top_cards)} top-level quest cards")

    questlines = []
    for card in top_cards:
        header = card.find(class_='chakra-card__header', recursive=False)
        h2 = header.find('h2') if header else None
        card_name = h2.get_text(strip=True) if h2 else ""

        body = card.find(class_='chakra-card__body', recursive=False)
        nested_cards = body.find_all(
            class_=lambda c: c and 'chakra-card' in c, recursive=False
        ) if body else []

        if nested_cards:
            # Questline with nested quests
            quests = []
            for nc in nested_cards:
                q = _parse_quest_card(nc)
                if q:
                    quests.append(q)
            if quests:
                questlines.append({
                    "questline": card_name,
                    "quests": quests,
                })
        else:
            # Standalone quest card
            q = _parse_quest_card(card)
            if q and q["name"]:
                questlines.append({
                    "questline": q["name"],
                    "quests": [q],
                })

    logger.info(f"Parsed {len(questlines)} questlines, "
                f"{sum(len(ql['quests']) for ql in questlines)} total quests")
    return questlines


def fetch_runewords() -> list[dict] | None:
    """
    Fetch and parse all runewords from hero-siege-helper.

    Returns list of runewords:
    [
        {
            "name": "Malice",
            "level": 15,
            "hand": "1H | 2H",
            "types": ["Claw", "Dagger", "Sword"],
            "runes": [
                {"name": "Uth", "rank": 6, "effect": "+5% of Damage Taken Recouped as Mana"},
                ...
            ]
        },
        ...
    ]
    """
    logger = logging.getLogger(LOGGING_NAME)
    soup = _fetch_soup("/runewords")
    if not soup:
        return None

    all_cards = soup.find_all(class_=lambda c: c and 'chakra-card' in c)
    runewords = []

    for card in all_cards:
        header = card.find(class_='chakra-card__header', recursive=False)
        body = card.find(class_='chakra-card__body', recursive=False)
        if not header or not body:
            continue

        h2 = card.find('h2', class_='chakra-heading')
        if not h2:
            continue

        h2_text = h2.get_text(separator=' ', strip=True)
        match = re.match(r'(.+?)\s*\[\s*(\d+)\s*\]', h2_text)
        if not match:
            continue

        name = match.group(1).strip()
        level = int(match.group(2))

        # Hand type (1H | 2H, etc.)
        p = header.find('p', class_='chakra-text')
        hand = p.get_text(strip=True) if p else ''

        # Compatible item types (spans with title attribute)
        type_els = header.find_all('span', attrs={'title': True})
        types = [s.get_text(strip=True) for s in type_els
                 if len(s.get_text(strip=True)) > 1]

        # Runes (in body)
        rune_els = body.find_all(class_=lambda c: c and 'runeword-rune' in c)
        runes = []
        for r in rune_els:
            rune_text = r.get_text(separator=' ', strip=True)
            parts = rune_text.split()
            rune_name = parts[-1] if parts else ''
            title = r.get('title', '')
            # Parse "Rank: 6\n+5% of Damage..." from title
            rank = 0
            effect = title
            rank_match = re.match(r'Rank:\s*(\d+)\n(.+)', title, re.DOTALL)
            if rank_match:
                rank = int(rank_match.group(1))
                effect = rank_match.group(2).strip()
            runes.append({'name': rune_name, 'rank': rank, 'effect': effect})

        runewords.append({
            'name': name, 'level': level, 'hand': hand,
            'types': types, 'runes': runes,
        })

    logger.info(f"Parsed {len(runewords)} runewords")
    return runewords


def fetch_runes() -> list[dict] | None:
    """
    Fetch and parse all runes from hero-siege-helper.

    Returns list of runes grouped by tier:
    [
        {
            "tier": "Low",
            "runes": [
                {"rank": 1, "level": 11, "name": "Ol", "stat": "+50 to Attack Rating"},
                ...
            ]
        },
        ...
    ]
    """
    logger = logging.getLogger(LOGGING_NAME)
    soup = _fetch_soup("/runes")
    if not soup:
        return None

    tiers = []
    # Runes are in tables, each preceded by an h2 heading (Low, Mid, High, Angelic)
    h2s = soup.find_all('h2', class_='chakra-heading')

    for h2 in h2s:
        tier_name = h2.get_text(strip=True)
        if tier_name in ('Runes', ''):
            continue

        # Find the next table after this heading
        parent = h2.parent
        table = None
        for sibling in parent.find_all_next('table'):
            table = sibling
            break

        if not table:
            continue

        rows = table.find('tbody')
        if not rows:
            continue

        runes = []
        for tr in rows.find_all('tr'):
            cells = tr.find_all('td')
            if len(cells) >= 4:
                rank = cells[0].get_text(strip=True)
                level = cells[1].get_text(strip=True)
                name = cells[2].get_text(strip=True)
                stat = cells[3].get_text(strip=True)
                runes.append({
                    'rank': int(rank) if rank.isdigit() else 0,
                    'level': int(level) if level.isdigit() else 0,
                    'name': name,
                    'stat': stat,
                })

        if runes:
            tiers.append({'tier': tier_name, 'runes': runes})

    total = sum(len(t['runes']) for t in tiers)
    logger.info(f"Parsed {total} runes in {len(tiers)} tiers")
    return tiers


# ─── Items (parsed from JS bundle) ───

def _extract_balanced_block(text: str, start: int) -> str | None:
    """Extract a balanced {} block from JS text."""
    depth = 0
    in_str = False
    esc = False
    i = start
    while i < len(text):
        c = text[i]
        if esc:
            esc = False
            i += 1
            continue
        if c == '\\':
            esc = True
            i += 1
            continue
        if c == '"':
            in_str = not in_str
        elif not in_str:
            if c == '{':
                depth += 1
            elif c == '}':
                depth -= 1
                if depth == 0:
                    return text[start:i + 1]
        i += 1
    return None


def _js_obj_to_json(js_str: str) -> str:
    """Convert JS object notation to valid JSON."""
    result = re.sub(r'(?<=[{,])\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*:', r'"\1":', js_str)
    result = result.replace('!0', 'true').replace('!1', 'false').replace('void 0', 'null')
    return result


def _find_item_data_chunk() -> str | None:
    """Find and fetch the JS chunk containing item data."""
    logger = logging.getLogger(LOGGING_NAME)
    try:
        resp = requests.get(f"{BASE_URL}/items", timeout=TIMEOUT)
        resp.raise_for_status()
    except Exception as e:
        logger.error(f"Failed to fetch /items page: {e}")
        return None

    js_urls = set(re.findall(r'/_next/static/chunks/[^"]+\.js', resp.text))
    dpl = re.search(r'dpl=([^"&]+)', resp.text)
    dpl_param = f"?dpl={dpl.group(1)}" if dpl else ""

    for url in js_urls:
        try:
            r = requests.get(f"{BASE_URL}{url}{dpl_param}", timeout=TIMEOUT)
            if 'globalItemList' in r.text and 'itemsFromSingleFiles' in r.text:
                logger.info(f"Found item data chunk: {url} ({len(r.text)} bytes)")
                return r.text
        except Exception:
            continue
    return None


def _find_stat_defs_chunk() -> str | None:
    """Find and fetch the JS chunk containing stat definitions."""
    logger = logging.getLogger(LOGGING_NAME)
    try:
        resp = requests.get(f"{BASE_URL}/items", timeout=TIMEOUT)
        resp.raise_for_status()
    except Exception:
        return None

    js_urls = set(re.findall(r'/_next/static/chunks/[^"]+\.js', resp.text))
    dpl = re.search(r'dpl=([^"&]+)', resp.text)
    dpl_param = f"?dpl={dpl.group(1)}" if dpl else ""

    for url in js_urls:
        try:
            r = requests.get(f"{BASE_URL}{url}{dpl_param}", timeout=TIMEOUT)
            if '"Stat ID":"total_damage_percent"' in r.text:
                return r.text
        except Exception:
            continue
    return None


def _parse_stat_defs(content: str) -> list[dict]:
    """Extract stat definitions array from JS chunk."""
    idx = content.find('[{"Stat ID":"total_damage_percent"')
    if idx < 0:
        return []
    depth = 0
    for i in range(idx, min(idx + 100000, len(content))):
        if content[i] == '[':
            depth += 1
        elif content[i] == ']':
            depth -= 1
            if depth == 0:
                try:
                    return json.loads(content[idx:i + 1])
                except json.JSONDecodeError:
                    return []
    return []


def _parse_items_from_js(content: str) -> list[dict]:
    """Extract all item objects from JS bundle."""
    pattern = re.compile(r'\{id:"[^"]+",name:"[^"]+",variants:\[')
    matches = list(pattern.finditer(content))

    items = []
    for m in matches:
        block = _extract_balanced_block(content, m.start())
        if not block:
            continue
        try:
            json_str = _js_obj_to_json(block)
            raw = json.loads(json_str)
        except json.JSONDecodeError:
            continue

        # Simplify: extract most recent version metadata + stats
        for variant in raw.get('variants', []):
            versions = variant.get('versions', [])
            if not versions:
                continue
            ver = versions[0]  # Most recent version
            meta = ver.get('metadata', {})
            name = meta.get('Item Name', raw.get('name', ''))
            if not name:
                continue

            stats = []
            for s in ver.get('stats', []):
                stat = {'id': s.get('Stat ID', '')}
                if 'Min Value1' in s:
                    stat['min'] = s['Min Value1']
                if 'Max Value1' in s:
                    stat['max'] = s['Max Value1']
                if 'Spell Name' in s:
                    stat['spell'] = s['Spell Name']
                if 'Class Name' in s:
                    stat['class'] = s['Class Name']
                if stat['id']:
                    stats.append(stat)

            items.append({
                'id': raw.get('id', ''),
                'name': name,
                'type': meta.get('Item Type', ''),
                'rarity': meta.get('Item Rarity', ''),
                'level': meta.get('Item Level Requirement', 0),
                'tier': meta.get('Item Tier', ''),
                'stats': stats,
            })

    return items


def fetch_items() -> dict | None:
    """
    Fetch and parse all items + stat definitions from hero-siege-helper.

    Returns:
    {
        "items": [...],     # Simplified item list
        "stat_defs": [...]  # Stat ID → display format mapping
    }
    """
    logger = logging.getLogger(LOGGING_NAME)

    content = _find_item_data_chunk()
    if not content:
        logger.error("Could not find item data chunk")
        return None

    items = _parse_items_from_js(content)
    logger.info(f"Parsed {len(items)} items from JS bundle")

    # Stat definitions (may be in a different chunk)
    stat_content = _find_stat_defs_chunk()
    stat_defs = _parse_stat_defs(stat_content) if stat_content else []
    logger.info(f"Parsed {len(stat_defs)} stat definitions")

    if not items:
        return None

    return {"items": items, "stat_defs": stat_defs}


# ─── Farm (zone drop locations, parsed from JS bundle) ───

def _find_farm_data_chunk() -> str | None:
    """Find and fetch the JS chunk containing farm zone→items mapping."""
    logger = logging.getLogger(LOGGING_NAME)
    try:
        resp = requests.get(f"{BASE_URL}/farm", timeout=TIMEOUT)
        resp.raise_for_status()
    except Exception as e:
        logger.error(f"Failed to fetch /farm page: {e}")
        return None

    js_urls = set(re.findall(r'/_next/static/chunks/[^"]+\.js', resp.text))
    dpl = re.search(r'dpl=([^"&]+)', resp.text)
    dpl_param = f"?dpl={dpl.group(1)}" if dpl else ""

    for url in js_urls:
        try:
            r = requests.get(f"{BASE_URL}{url}{dpl_param}", timeout=TIMEOUT)
            # Farm chunk has JSON.parse('{"Rat Den":["..."],...}')
            if "JSON.parse('" in r.text and '"Rat Den":["' in r.text:
                logger.info(f"Found farm data chunk: {url} ({len(r.text)} bytes)")
                return r.text
        except Exception:
            continue
    return None


def _find_zone_data_chunk() -> str | None:
    """Find and fetch the JS chunk containing zone name→code mapping."""
    logger = logging.getLogger(LOGGING_NAME)
    try:
        resp = requests.get(f"{BASE_URL}/farm", timeout=TIMEOUT)
        resp.raise_for_status()
    except Exception as e:
        logger.error(f"Failed to fetch /farm page: {e}")
        return None

    js_urls = set(re.findall(r'/_next/static/chunks/[^"]+\.js', resp.text))
    dpl = re.search(r'dpl=([^"&]+)', resp.text)
    dpl_param = f"?dpl={dpl.group(1)}" if dpl else ""

    for url in js_urls:
        try:
            r = requests.get(f"{BASE_URL}{url}{dpl_param}", timeout=TIMEOUT)
            if 'zone:"3-1",name:"Corrupted Oasis"' in r.text:
                logger.info(f"Found zone data chunk: {url} ({len(r.text)} bytes)")
                return r.text
        except Exception:
            continue
    return None


def _parse_farm_json(content: str) -> dict | None:
    """Extract the zone→items JSON from the farm JS chunk.

    The data lives inside a JSON.parse('...') call with the structure:
    {"Zone Name": ["Item1", "Item2", ...], ...}
    """
    marker = '"Rat Den"'
    idx = content.find(marker)
    if idx < 0:
        return None

    # Walk back to find JSON.parse('
    start = content.rfind("JSON.parse('", max(0, idx - 300), idx)
    if start < 0:
        return None
    json_start = start + len("JSON.parse('")

    # Find the closing ')
    json_end = content.find("')", json_start)
    if json_end < 0:
        return None

    raw = content[json_start:json_end]
    # Fix JS string escaping: \' (backslash + single quote) → just single quote
    fixed = raw.replace(chr(92) + chr(39), chr(39))

    try:
        return json.loads(fixed)
    except json.JSONDecodeError:
        return None


def _parse_zone_codes(content: str) -> dict:
    """Extract zone name→code mapping from the zones JS chunk.

    Parses zone:"X-Y" then finds the nearest name:"..." in a 300-char window.
    Handles varying field order (zone,name vs zone,roomUrls,...,name).
    """
    zones = {}
    for m in re.finditer(r'zone:"(\d+-\d+(?:-\d+)?)"', content):
        code = m.group(1)
        window = content[m.start():min(len(content), m.start() + 300)]
        nm = re.search(r'name:"([^"]+)"', window)
        if nm:
            zones[nm.group(1)] = code
    return zones


_ZONE_CODE_RE = re.compile(r'^\d+-(?:\d+|BD|D)$')

# Boss names (drop from specific bosses, not regular zones)
_BOSS_NAMES = {
    'Uber Damien', 'Uber Reaper', 'Uber Gabriel',
    'Sung Lee', 'Architect of Ruin', 'Possessed Luna',
    'Amun Ra', 'Endrixia', 'Grimbone', 'The Sheep King',
    'Gabriel', 'King Rakhul', 'Mevius',
}

# Special area names (not regular act zones)
_SPECIAL_AREAS = {
    'Sheeponia', 'Unstable Rift', 'Colossal Chest', 'Ruby Chest',
    'Eternal Battlefield', 'Chaos Tower', 'Rogue Chaos Tower',
    'Gamba Machine', 'Generic Chest', 'Wormhole',
    'Chaos Pillar', 'Shadow Realm', 'Bifrost',
    'Challenge Dungeon', 'Circle of Hatred', 'Mimic',
    'Curacan Hollow',
}


def _classify_farm_key(key: str, zone_codes: dict) -> tuple:
    """Classify a farm data key into (kind, zone_code_or_none).

    Returns:
        ("zone_code", code)     — key IS a zone code like "1-1", "3-BD"
        ("zone_name", code)     — key is a zone name that maps to a code
        ("dungeon", None)       — dungeon/sub-zone name (Rat Den, etc.)
        ("boss", None)          — boss-specific drop
        ("rare_boss", None)     — 1:100 boss drop
        ("special", None)       — special areas
        ("crafting", None)      — crafted items
        ("quest", None)         — quest rewards
    """
    k = key.strip()

    # Direct zone code: "1-1", "3-BD", "2-D"
    if _ZONE_CODE_RE.match(k):
        return ("zone_code", k)

    # Known zone name → zone code
    if k in zone_codes:
        return ("zone_name", zone_codes[k])

    # 1:100 boss patterns
    if re.match(r'1:\d+ ', k):
        return ("rare_boss", None)

    # Bosses
    if k in _BOSS_NAMES or k == 'HP':
        return ("boss", None)

    # Crafting
    if 'Crafting' in k or 'Tarot' in k:
        return ("crafting", None)

    # Quest
    if k == 'Quest':
        return ("quest", None)

    # Special areas
    if k in _SPECIAL_AREAS:
        return ("special", None)

    # Dungeon or unknown sub-zone (Rat Den, Northern Post, Chilling Cavern, etc.)
    return ("dungeon", None)


def _invert_farm_data(zone_to_items: dict, zone_codes: dict) -> tuple:
    """Convert zone→items dict to item-centric list + zone_names lookup.

    Returns (items_list, zone_names_dict):
        items_list: [{"name": str, "zones": [code], "sources": [{"type":..., "name":...}]}, ...]
        zone_names_dict: {code: name, ...}
    """
    # Build reverse zone_names: code → name
    zone_names = {v: k for k, v in zone_codes.items()}

    # Accumulate per-item data
    item_map = {}  # item_name → {"zones": set, "sources": list}

    for farm_key, item_names in zone_to_items.items():
        kind, code = _classify_farm_key(farm_key, zone_codes)

        for item_name in item_names:
            if item_name not in item_map:
                item_map[item_name] = {"zones": set(), "sources": []}

            entry = item_map[item_name]

            if kind in ("zone_code", "zone_name") and code:
                entry["zones"].add(code)
                if code not in zone_names:
                    zone_names[code] = farm_key
            elif kind == "dungeon":
                # Dungeons are sub-zones; store as zone with the key as name
                entry["zones"].add(farm_key)
                zone_names[farm_key] = farm_key
            else:
                # Non-zone source: boss, special, crafting, quest, rare_boss
                src = {"type": kind, "name": farm_key}
                if src not in entry["sources"]:
                    entry["sources"].append(src)

    # Build final items list
    items = []
    for name, data in sorted(item_map.items()):
        item = {"name": name, "zones": sorted(data["zones"])}
        if data["sources"]:
            item["sources"] = data["sources"]
        items.append(item)

    return items, zone_names


def fetch_farm() -> dict | None:
    """
    Fetch and parse farm zone→item drop location data from hero-siege-helper.

    Returns:
    {
        "zone_names": {"1-1": "Outskirts of Inoya", ...},
        "items": [
            {
                "name": "Ancient Aegis",
                "zones": ["3-1", "3-2", "3-3"],
                "sources": [{"type": "special", "name": "Colossal Chest"}]  # optional
            },
            ...
        ]
    }
    """
    logger = logging.getLogger(LOGGING_NAME)

    # 1. Get farm zone→items mapping from JS chunk
    farm_content = _find_farm_data_chunk()
    if not farm_content:
        logger.error("Could not find farm data chunk")
        return None

    zone_to_items = _parse_farm_json(farm_content)
    if not zone_to_items:
        logger.error("Failed to parse farm JSON data")
        return None
    logger.info(f"Farm raw: {len(zone_to_items)} zone entries")

    # 2. Get zone name→code mapping from zones JS chunk
    zone_content = _find_zone_data_chunk()
    zone_codes = _parse_zone_codes(zone_content) if zone_content else {}
    logger.info(f"Zone codes: {len(zone_codes)} mappings")

    # 3. Convert to item-centric structure
    items, zone_names = _invert_farm_data(zone_to_items, zone_codes)
    logger.info(f"Farm parsed: {len(items)} items, {len(zone_names)} zones")

    if not items:
        return None

    return {"zone_names": zone_names, "items": items}
